#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    receipe-search-web-80-http:
      entrypoints:
        - http-33001
      rule: HostRegexp(`^receipe-search\.ddev\.site$`)
      
      service: "receipe-search-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "receipe-search-redirectHttps"
    receipe-search-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^receipe-search\.ddev\.site$`)
      
      service: "receipe-search-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "receipe-search-redirectHttps"
    receipe-search-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^receipe-search\.ddev\.site$`)
      
      service: "receipe-search-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "receipe-search-redirectHttps"
    
    
    
    receipe-search-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^receipe-search\.ddev\.site$`)
      
      service: "receipe-search-web-80"
      ruleSyntax: v3
      
      tls: true
      
    receipe-search-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^receipe-search\.ddev\.site$`)
      
      service: "receipe-search-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    receipe-search-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^receipe-search\.ddev\.site$`)
      
      service: "receipe-search-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    receipe-search-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    receipe-search-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-receipe-search-web:80
        
    receipe-search-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-receipe-search-web:8025
        
    
    
    receipe-search-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-receipe-search-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/receipe-search.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/receipe-search.key